apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-hbfb-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios@sha256:167d971cb289ed8db6aaf59185de8a1e3c2dafca194ad9eff4d746695c688d69
        name: my-go
        resources: {}
status: {}
